### ISSUE TITLE
Flight mode enabled when players join

### ISSUE THREAD

**Issue by sulubsquared** [DimBis/FadMad#2]
I'm not sure if it's your plugin causing this but I've been receiving this issue when I installed this plugin.

Issue: Players can fly at spawn and warps

Error in Console: None

**Comment by ghost** [comment]
The plug-in does not have anything to do with the flight mode. It might be one of your other plug-ins doing that behavior, you should start removing then re-adding them one by one to see if they're compatible with this core.
