### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BLAST1718** [DimBis/FadMad#5]
Are you going to maintain the v1 or drop it?

**Comment by ghost** [comment]
Excuse me?

**Comment by BLAST1718** [comment]
why excuse me?

**Comment by ghost** [comment]
I didn't understand what you meant by "Are u gonna update this or the other **one**"

**Comment by BLAST1718** [comment]
are u gonna update the ver 1 or ver 2?

**Comment by ghost** [comment]
You can get the v2 from here https://github.com/DimBis/FadMad/tree/beta

**Comment by BLAST1718** [comment]
will u update that?

**Comment by BLAST1718** [comment]
like the ver 1?

**Comment by ghost** [comment]
The version 1 (the master branch) will no longer be maintained due to feature freeze, most of it is hard coded and i don't even know how it even works. It's just a two years old code, the v2 (beta branch) is being maintained but not very often, you can PR if you want to.

**Comment by BLAST1718** [comment]
what is pr?

**Comment by BLAST1718** [comment]
the ver 1 is pretty good tho

**Comment by ghost** [comment]
> what is pr?

pr = pull request

**Comment by ghost** [comment]
> the ver 1 is pretty good tho

it is good indeed, but not very customisable.
